# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: microservice.proto for package 'micro_service.pb'
# Original file comments:
# Protocol version: v.1
#

require 'grpc'
require 'pb/microservice_pb'

module MicroService
  module Pb
    module MicroService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'micro_service.pb.MicroService'

        rpc :Ping, ::MicroService::Pb::EchoRequest, ::MicroService::Pb::EchoResponse
        rpc :PutFile, ::MicroService::Pb::PutFileRequest, ::MicroService::Pb::PutFileResponse
        rpc :GetFile, ::MicroService::Pb::GetFileRequest, ::MicroService::Pb::GetFileResponse
        rpc :DeleteFile, ::MicroService::Pb::DeleteFileRequest, ::MicroService::Pb::DeleteFileResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
