# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservice.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("microservice.proto", :syntax => :proto3) do
    add_message "micro_service.pb.EchoRequest" do
      optional :echo_text, :string, 1
    end
    add_message "micro_service.pb.EchoResponse" do
      optional :echo_text, :string, 1
    end
    add_message "micro_service.pb.PutFileRequest" do
      optional :file_key, :string, 1
      optional :file, :bytes, 2
    end
    add_message "micro_service.pb.PutFileResponse" do
      optional :result, :string, 1
    end
    add_message "micro_service.pb.GetFileRequest" do
      optional :file_key, :string, 1
    end
    add_message "micro_service.pb.GetFileResponse" do
      optional :result, :string, 1
      optional :file, :bytes, 2
    end
    add_message "micro_service.pb.DeleteFileRequest" do
      optional :file_key, :string, 1
    end
    add_message "micro_service.pb.DeleteFileResponse" do
      optional :result, :string, 1
    end
  end
end

module MicroService
  module Pb
    EchoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("micro_service.pb.EchoRequest").msgclass
    EchoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("micro_service.pb.EchoResponse").msgclass
    PutFileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("micro_service.pb.PutFileRequest").msgclass
    PutFileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("micro_service.pb.PutFileResponse").msgclass
    GetFileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("micro_service.pb.GetFileRequest").msgclass
    GetFileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("micro_service.pb.GetFileResponse").msgclass
    DeleteFileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("micro_service.pb.DeleteFileRequest").msgclass
    DeleteFileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("micro_service.pb.DeleteFileResponse").msgclass
  end
end
